### ISSUE TITLE
em_german_leo_mistral not available @ Hugging Face

### ISSUE THREAD

**Issue by jannikbuscha** [jphme/EM_German#13]
when im executing this code:
```py
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "jphme/em_german_leo_mistral"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
```

im getting this error:
```
Traceback (most recent call last):
  File "C:\Users\Jannik\PycharmProjects\pythonProject2\token_stopper.py", line 34, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_name)
  File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 998, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 710, in __getitem__
    raise KeyError(key)
KeyError: 'mistral'
```

**Comment by jannikbuscha** [comment]
> when im executing this code:
> 
> ```python
> from transformers import AutoTokenizer, AutoModelForCausalLM
> 
> model_name = "jphme/em_german_leo_mistral"
> tokenizer = AutoTokenizer.from_pretrained(model_name)
> model = AutoModelForCausalLM.from_pretrained(model_name)
> ```
> 
> im getting this error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Jannik\PycharmProjects\pythonProject2\token_stopper.py", line 34, in <module>
>     model = AutoModelForCausalLM.from_pretrained(model_name)
>   File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
>     config, kwargs = AutoConfig.from_pretrained(
>   File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 998, in from_pretrained
>     config_class = CONFIG_MAPPING[config_dict["model_type"]]
>   File "C:\Users\Jannik\PycharmProjects\pythonProject2\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 710, in __getitem__
>     raise KeyError(key)
> KeyError: 'mistral'
> ```

updating to the latest version of transformers has solved the problem.
